sudo: required

language: shell

services:
  - docker

env:
  - GOSS_FILES_STRATEGY=cp

script:
  - sudo apt-get update
  # Don't do that else it's too slow : - sudo apt-get upgrade
  - sudo apt-get install -y --no-install-recommends curl
  - curl -fsSL https://goss.rocks/install | sudo sh
  - scripts/test.sh 1.6-debian
  - scripts/test.sh 1.10-debian
  - scripts/test.sh 1.14-debian
  - scripts/test.sh 1.17-alpine
