sudo: required

language: shell

services:
  - docker

env:
  - GOSS_FILES_STRATEGY=cp

script:
  - sudo apt-get update && apt-get upgrade && apt-get install -y --no-install-recommends curl
  - curl -fsSL https://goss.rocks/install | sudo sh
  - ./test.sh 1.10-debian
  - ./test.sh 1.15-alpine
