version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: docker:18-dind
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install tools
          command: |
            # rather than give internet scripts SU rights, we install to local user bin and add to path
            apk update && apk add bash curl
            curl -fsSL https://goss.rocks/install | sh

      - run:
          name: Test Debian Image 1.6
          command: |
            export GOSS_FILES_STRATEGY=cp
            scripts/test.sh 1.6-debian

      - run:
          name: Test Debian Image 1.10
          command: |
            export GOSS_FILES_STRATEGY=cp
            scripts/test.sh 1.10-debian

      - run:
          name: Test Alpine Image 1.14
          command: |
            export GOSS_FILES_STRATEGY=cp
            scripts/test.sh 1.14-debian

      - run:
          name: Test Alpine Image 1.17
          command: |
            export GOSS_FILES_STRATEGY=cp
            scripts/test.sh 1.17-alpine
